In [1]:
#List slicing
#list[start:end:step]
list=[1,2,3,4,5]
list[1:]

[2, 3, 4, 5]

In [2]:
list[1:3]

[2, 3]

In [4]:
list[1:6:2]

[2, 4]

In [5]:
#-->reversing the list
list[::-1]

[5, 4, 3, 2, 1]

In [6]:
list[::2]

[1, 3, 5]

In [7]:
list[1:4]=[10,20,30]
list

[1, 10, 20, 30, 5]

In [8]:
del list[1:3]
list

[1, 30, 5]

In [9]:
list=[1,2,3]
list1=[4,5,6]
list+list1

[1, 2, 3, 4, 5, 6]

In [10]:
#copying the list
list=[1,2,3]
secondList=list[:]
secondList

[1, 2, 3]

In [12]:
#skip every third element from index 1
list=[1,2,3,4,5,6,7,8]
list[1::3]

[2, 5, 8]

In [17]:
s="satya"
output_string="saTYA"
s[:1]+s[1:2]+s[2:].upper()

'saTYA'

In [19]:
#dictionaries with slicing
student={
    "name":"sample",
    "rollno":123,
    "subjects":["maths","physics","social"]
}
student

{'name': 'sample', 'rollno': 123, 'subjects': ['maths', 'physics', 'social']}

In [20]:
student["name"]

'sample'

In [21]:
student["subjects"]

['maths', 'physics', 'social']

In [22]:
student["subjects"][0]

'maths'

In [23]:
student["subjects"][::2]

['maths', 'social']

In [24]:
student.get("name")

'sample'

In [25]:
student.update({'name': 'sample1', 'rollno': 1234, 'subjects': ['maths', 'physics']})

In [26]:
student

{'name': 'sample1', 'rollno': 1234, 'subjects': ['maths', 'physics']}

In [27]:
student.keys()

dict_keys(['name', 'rollno', 'subjects'])

In [28]:
student.values()

dict_values(['sample1', 1234, ['maths', 'physics']])

In [30]:
student.items()

dict_items([('name', 'sample1'), ('rollno', 1234), ('subjects', ['maths', 'physics'])])

In [34]:
s1,s2={1,2,3,4},{5,6,7,8}
s2-s1

{5, 6, 7, 8}

In [35]:
s1.union(s2)

{1, 2, 3, 4, 5, 6, 7, 8}

In [38]:
s1,s2={1,2,3,4},{5,2,7,8}
s1.intersection(s2)

{2}

In [39]:
#Datascience
#1.Numpy
#2.Pandas
#3. Matplotlib or seaborn

In [40]:
#Numpy-->it involves in statistics,mathematics,analyze and interpret complex data sets
#Numpy is a fundamental package for multi dimensional arrays and matrices.
#list-->storing different data types
#numpy-->storing only single data type
#numpy is mainly dealing with arrays

In [41]:
#Key features in numpy:
#1. it is similar to list and it is storing one data type and it is faster and memeory efficient
#2. it will allows you to perform element wise operations on arrays without explicitly writing loops
#3. using numpy we can do trigonometry,linear algebra
#4.

In [42]:
pip install numpy

In [43]:
import numpy as np

In [46]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [47]:
type(a)

numpy.ndarray

In [48]:
a.ndim

1

In [49]:
a.size

5

In [50]:
a[0]

1

In [51]:
a[-1]

5

In [52]:
a

array([1, 2, 3, 4, 5])

In [53]:
a=np.array([1,2,3,4,5],dtype=float)

In [54]:
a

array([1., 2., 3., 4., 5.])

In [55]:
type(a)

numpy.ndarray

In [56]:
a=np.array([1,2,3,"sai"],dtype=int)

ValueError: invalid literal for int() with base 10: 'sai'

In [59]:
#range(1,10)
a=np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [61]:
a=np.arange(5,100,0.6)
a

array([ 5. ,  5.6,  6.2,  6.8,  7.4,  8. ,  8.6,  9.2,  9.8, 10.4, 11. ,
       11.6, 12.2, 12.8, 13.4, 14. , 14.6, 15.2, 15.8, 16.4, 17. , 17.6,
       18.2, 18.8, 19.4, 20. , 20.6, 21.2, 21.8, 22.4, 23. , 23.6, 24.2,
       24.8, 25.4, 26. , 26.6, 27.2, 27.8, 28.4, 29. , 29.6, 30.2, 30.8,
       31.4, 32. , 32.6, 33.2, 33.8, 34.4, 35. , 35.6, 36.2, 36.8, 37.4,
       38. , 38.6, 39.2, 39.8, 40.4, 41. , 41.6, 42.2, 42.8, 43.4, 44. ,
       44.6, 45.2, 45.8, 46.4, 47. , 47.6, 48.2, 48.8, 49.4, 50. , 50.6,
       51.2, 51.8, 52.4, 53. , 53.6, 54.2, 54.8, 55.4, 56. , 56.6, 57.2,
       57.8, 58.4, 59. , 59.6, 60.2, 60.8, 61.4, 62. , 62.6, 63.2, 63.8,
       64.4, 65. , 65.6, 66.2, 66.8, 67.4, 68. , 68.6, 69.2, 69.8, 70.4,
       71. , 71.6, 72.2, 72.8, 73.4, 74. , 74.6, 75.2, 75.8, 76.4, 77. ,
       77.6, 78.2, 78.8, 79.4, 80. , 80.6, 81.2, 81.8, 82.4, 83. , 83.6,
       84.2, 84.8, 85.4, 86. , 86.6, 87.2, 87.8, 88.4, 89. , 89.6, 90.2,
       90.8, 91.4, 92. , 92.6, 93.2, 93.8, 94.4, 95

In [62]:
#linspace
a=np.linspace(2,5,7)
#2 is starting value and 5 is the ending value and 7 is the number of elements inside the array
a

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [63]:
a=np.linspace(2,5,70)
a

array([2.        , 2.04347826, 2.08695652, 2.13043478, 2.17391304,
       2.2173913 , 2.26086957, 2.30434783, 2.34782609, 2.39130435,
       2.43478261, 2.47826087, 2.52173913, 2.56521739, 2.60869565,
       2.65217391, 2.69565217, 2.73913043, 2.7826087 , 2.82608696,
       2.86956522, 2.91304348, 2.95652174, 3.        , 3.04347826,
       3.08695652, 3.13043478, 3.17391304, 3.2173913 , 3.26086957,
       3.30434783, 3.34782609, 3.39130435, 3.43478261, 3.47826087,
       3.52173913, 3.56521739, 3.60869565, 3.65217391, 3.69565217,
       3.73913043, 3.7826087 , 3.82608696, 3.86956522, 3.91304348,
       3.95652174, 4.        , 4.04347826, 4.08695652, 4.13043478,
       4.17391304, 4.2173913 , 4.26086957, 4.30434783, 4.34782609,
       4.39130435, 4.43478261, 4.47826087, 4.52173913, 4.56521739,
       4.60869565, 4.65217391, 4.69565217, 4.73913043, 4.7826087 ,
       4.82608696, 4.86956522, 4.91304348, 4.95652174, 5.        ])

In [64]:
#logspace
a=np.logspace(2,5,3)
#log(2) is starting value and log(5) is the ending value and 3 is the number of elements inside the array
a

array([   100.        ,   3162.27766017, 100000.        ])

In [65]:
#zeros
a=np.zeros(5)
#by default it is float type n number of zeros it will display
a

array([0., 0., 0., 0., 0.])

In [67]:
a=np.zeros(5,dtype=int)
a

array([0, 0, 0, 0, 0])

In [72]:
a=np.random.randint(4,100)
a

99

In [74]:
a=np.random.randint(0,100,50)
a

array([ 4, 43, 46, 58, 66, 86, 76, 28, 70, 68, 51, 98, 23, 51,  3, 33, 81,
        2, 29, 26, 50,  4, 64, 37, 54,  7, 49, 47, 82, 42, 56, 24, 10, 90,
       76, 68, 31, 67, 11,  2, 32,  9, 12, 32, 25,  5, 15, 86, 32,  1])

In [75]:
a=np.random.rand(5)
#it will generate random elements from 0
a

array([0.26872158, 0.41378531, 0.14148328, 0.2439885 , 0.20103355])

In [76]:
#collection of 1d array is 2d array

In [78]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [79]:
type(a)

numpy.ndarray

In [80]:
a.ndim

2

In [81]:
a[0][1]

2

In [82]:
a[1][1]

7

In [ ]:
[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]
a[0][2]
a[1][2]
a[2]

In [84]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [90]:
#reshape
a=np.arange(30)
a
# a.reshape(5,6)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [92]:
a.reshape(4,7)

ValueError: cannot reshape array of size 30 into shape (4,7)

In [93]:
a.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [94]:
a=np.random.randint(45,size=20).reshape(4,5)
a

array([[ 9, 34, 16, 33, 24],
       [22,  3, 15,  5, 21],
       [17, 29, 41, 42, 23],
       [22, 14,  3, 16, 22]])

In [95]:
a.reshape(5,4)

array([[ 9, 34, 16, 33],
       [24, 22,  3, 15],
       [ 5, 21, 17, 29],
       [41, 42, 23, 22],
       [14,  3, 16, 22]])

array([[ 3],
       [29]])