In [1]:
import numpy as np

In [2]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
a1=a.reshape(4,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
a1[2:3:2,2:4:1]

array([[12, 13]])

In [ ]:
a[2:3:2]-->2nd row it will select
[10,11,12,13,14]
a[2:4:1]-->2nd and 3rd column it will select
[12,13]

In [8]:
#To create 3dim arrays we can use arange method

In [9]:
a=np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
a1=a.reshape(2,3,5)
a1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [11]:
a1.ndim

3

In [12]:
a1[:]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [13]:
a1[:,1:2,1:4]

array([[[ 6,  7,  8]],

       [[21, 22, 23]]])

In [15]:
a1[::,1:2:1,1:4:1]

array([[[ 6,  7,  8]],

       [[21, 22, 23]]])

In [14]:
#1st value represent the faces
#2nd value represent rows
#3rd value represent columns

In [ ]:
a[1:2]
[5,6,7,8,9]
[20,21,22,23,24]
a[1:4]
[6,7,8]
[21,22,23]

In [17]:
a1[0:1:1,1:2:1,1:4:1]

array([[[6, 7, 8]]])

In [21]:
a1=np.arange(1,3)
a2=np.arange(6,8)

In [22]:
a1,a2

(array([1, 2]), array([6, 7]))

In [23]:
a1+a2

array([7, 9])

In [24]:
a1*a2

array([ 6, 14])

In [25]:
a1-a2

array([-5, -5])

In [26]:
np.sin(4)

-0.7568024953079282

In [27]:
dir(a1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [28]:
a1.sum()

3

In [29]:
a1

array([1, 2])

In [30]:
a1,a2

(array([1, 2]), array([6, 7]))

In [31]:
a=np.arange(20).reshape(4,5)

In [32]:
a1=np.arange(20).reshape(4,5)

In [34]:
a1,a

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]))

In [37]:
np.hstack((a,a1))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [38]:
np.vstack((a,a1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
a=np.arange(60).reshape(10,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [43]:
a1=np.vsplit(a,2)

In [41]:
a1

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]])]

In [44]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [45]:
a.itemsize*len(a)

40

In [46]:
a.itemsize

8

In [47]:
import sys

In [48]:
sys.getsizeof(a[0])

32

In [49]:
#time

In [50]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [51]:
import time

In [58]:
t=time.time()
a1+a2
print((time.time()-t)*1000)

0.18405914306640625


In [ ]:
before execution i started at 6:19pm
a1+a2-->it will take 1min
time.time() 6:20

In [59]:
#pandas-->it is a library  used for data manipulation in python
#it is used to create the dataframes
#you can store any type like csv or excel
#data manipulation: by using merging, reshaping, slicing,indexing
#data cleaning: handling missing data or removing unwanted data and performing the transformation tasks
#data analysis: mean ,median or std deviation we can fill using these values


In [60]:
import pandas as pd

In [61]:
pip install pandas

In [ ]:
import pandas as pd