In [1]:
#creating 3d array by using arange method

In [9]:
import numpy as np
a=np.arange(30).reshape(5,6)
a #6*5=30

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [10]:
#import numpy as np
a=np.arange(30).reshape(2,3,5)
a ##2*3*5=30

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [11]:
a[:]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [13]:
a[:,1:2,1:4]

array([[[ 6,  7,  8]],

       [[21, 22, 23]]])

In [14]:
a[0:2,1:2,1:4]

array([[[ 6,  7,  8]],

       [[21, 22, 23]]])

In [15]:
a[0:2:1,1:2:1,1:4:1] #faces,rows,columns

array([[[ 6,  7,  8]],

       [[21, 22, 23]]])

In [20]:
a[0:1,::2,0:5:4]

array([[[ 0,  4],
        [10, 14]]])

In [35]:
a[::-1,2:3:1,1:4:2]

array([[[26, 28]],

       [[11, 13]]])

In [39]:
a=np.random.randint(2,50,50).reshape(5,2,5)
a

array([[[27, 49,  3, 30, 11],
        [ 8, 36,  7, 11, 30]],

       [[40, 20, 19,  2,  7],
        [46, 25, 34, 21, 39]],

       [[17, 16, 46,  6,  6],
        [40, 43, 12,  9, 41]],

       [[26,  5, 25,  8, 45],
        [12, 31, 48, 22,  6]],

       [[39, 35, 47, 30,  6],
        [ 6, 37, 43, 31, 29]]])

In [42]:
a[0:3,0:1,0:4:2]

array([[[27,  3]],

       [[40, 19]],

       [[17, 46]]])

In [49]:
a[4:0:-1,1::,4::]

array([[[29]],

       [[ 6]],

       [[41]],

       [[39]]])

In [50]:
#basic operations in numpy array

In [51]:
a1=np.arange(1,5)
a2=np.arange(5,9)

In [52]:
a1,a2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [53]:
a1+a2

array([ 6,  8, 10, 12])

In [54]:
a1*a2

array([ 5, 12, 21, 32])

In [56]:
a1-a2

array([-4, -4, -4, -4])

In [57]:
a1/a2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [58]:
np.sin(4)

-0.7568024953079282

In [59]:
a1=a1.reshape(2,2)
a1

array([[1, 2],
       [3, 4]])

In [60]:
a2=a2.reshape(2,2)
a2

array([[5, 6],
       [7, 8]])

In [61]:
a1+a2

array([[ 6,  8],
       [10, 12]])

In [62]:
a1.dot(a2)

array([[19, 22],
       [43, 50]])

In [63]:
a1@a2

array([[19, 22],
       [43, 50]])

In [64]:
dir(a1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [65]:
a1.sum()

10

In [66]:
a1.sum(axis=0)

array([4, 6])

In [67]:
for i in a1:
    print(i*5)

[ 5 10]
[15 20]


In [68]:
#join numpy array

In [69]:
a1

array([[1, 2],
       [3, 4]])

In [70]:
a2

array([[5, 6],
       [7, 8]])

In [71]:
np.hstack((a1,a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [72]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#splitting numpy array

In [74]:
a=np.arange(60).reshape(10,6)

In [75]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [77]:
x1=np.vsplit(a,2)

In [79]:
x1

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]])]

comparision between list and numpy array

#1.timing and memory
list is taking huge memory
two lists calcultions huge time

In [81]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [83]:
a.itemsize*len(a) ##total memory taken each number takes 4 bytes

20

In [84]:
b=[1,2,3,4,5]

In [85]:
import sys

In [86]:
sys.getsizeof(a[0]) #each element takes

28

In [87]:
#time

In [93]:
n=100000

In [98]:
a1=np.array([1,2,3])
a2=np.array([2,3,4])
a1+a2

array([3, 5, 7])

In [94]:
import time

In [99]:
s=time.time()
a1+a2
print((time.time()-s)*1000)
#to calculate current time use time.time()
#to calculate toatal time subtarct

0.0


In [100]:
z1=[1,2,3]
z2=[3,4,5]
list(map(lambda x,y:x+y,z1,z2))

[4, 6, 8]

In [107]:
s=time.time()
list(map(lambda x,y:x+y,z1,z2))
print((time.time()-s)*1000)

0.0


In [1]:
500/1

500.0

In [6]:
(16/6)

2.6666666666666665